# Generated by Django 4.1.1 on 2022-09-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Item name')),
                ('description', models.CharField(max_length=200, verbose_name='Discription')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
            ],
        ),
    ]
